spring.application.name=springBoot-0226

# 1 ??? ?? ?? ??222
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/webdb
spring.datasource.username=webuser
spring.datasource.password=webuser

# 2, ???? ??, ???? ??  info, ??? ???? ???? debug ???
logging.level.org.springframework=debug
logging.level.com.busanit501=debug


# 3, spring data jpa ??, ?? ???, ??? ???? ?? ??.
# ??????? ??? ?? ???, ???? ??? ??.
# ??, ?? ?????, ????? ?????, ??? ??? ??, ?? ???? ????.

# ?? ??,
# none : DDL ?? ??.
# create-drop : ??? ?, DDL ???? ???,
# ??? ??,
# create : ??? ???, ??? ?? ?? ??
# validate : ??? ??? ???? ??
# ??, ?? ??, update // ??? create ? ?? ? ????(?? update ? ?? ??)
# ?? ??, none, validate , ? ????.
spring.jpa.hibernate.ddl-auto=update
# ?? ?? ???, sql ??? ??? ??? ?? ???.
spring.jpa.properties.hibernate.format_sql=true
# sql ??? ????? ????? ??.2233
spring.jpa.show-sql=true

